%Project Title: Road Sign Recognition
%Module Title: Network Training
%Authors: Damiano Vandi, Matteo Lenti, Filippo Cenonfolo

%Define options for the training 
options = trainingOptions('adam', ...
    'InitialLearnRate',0.001, ...
    'MaxEpochs',100, ...
    'MiniBatchSize',128, ...
    'Shuffle','every-epoch', ...
    'ValidationData',resizedImdsValidation, ...
    'ValidationFrequency',307, ...
    'Verbose',false, ...
    'Plots','training-progress');

%Launch the network training
net = trainNetwork(resizedImdsTrain,layers,options);%todo change name of the network